### ISSUE TITLE
Optimization: Crankshaft RSub is suboptimum for s390

### ISSUE THREAD

**Issue by john-yan** [ibmruntimes/v8#27]
Here is the observation in GameBoyCore.intializeWhiteNoise function compiled by crankshaft:

x64 code:
                  **;;; <@126,#87> constant-i**
0x2626d892529c   380  41bc01000000   movl r12,0x1
                  **;;; <@128,#92> sub-i**
0x2626d89252a2   386  452be3         subl r12,r11

s390 code:
                  **;;; <@132,#92> rsub-i**                                                                                                                       
 0x5c034b5256   566  c00800000000   iihf r0,0                                                                                                                  
 0x5c034b525c   572  c00900000001   iilf r0,1                                                                                                                  
 0x5c034b5262   578  b91400dd       lgfr r13,r13                                                                                                               
 0x5c034b5266   582  b90300dd       lcgr r13,r13                                                                                                               
 0x5c034b526a   586  b90800d0       agr  r13,r0   

Consider removing rsub on s390 given that s390 doesn't have reversed subtract instruction.

**Comment by joransiu** [comment]
@john-yan: nice find!   Do you see rsub-i being a common pattern?

**Comment by john-yan** [comment]
it's in a hot loop of an expensive function.

**Comment by joransiu** [comment]
I meant, in general, say across the other Octane benchmarks.

**Comment by john-yan** [comment]
140445 instances of overall benchmark RSubI. It's not very common compare to other hot opcodes

**Comment by john-yan** [comment]
https://codereview.chromium.org/2561673002
