### ISSUE TITLE
PPC/S390: Delay allocation of code-embedded heap numbers.

### ISSUE THREAD

**Issue by sampsongao** [ibmruntimes/v8#47]
When porting [Issue 2900683002](https://codereview.chromium.org/2900683002), we found some obstacle in allocating and relocating heap number. The initial [CL](https://codereview.chromium.org/2921473003/) for porting was not working.

We leave out the heap number related change for now ([Issue 2929843002](https://codereview.chromium.org/2929843002/)) and we will investigate this issue further in the future.

Summary:
Following CL needs to be ported:
- [x] https://codereview.chromium.org/2900683002  - [port CL](https://chromium-review.googlesource.com/c/581744/)
- [x] https://chromium-review.googlesource.com/c/548078/  - [port CL](https://chromium-review.googlesource.com/c/581744/)
- [x] https://chromium-review.googlesource.com/c/561015/  - [port CL](https://chromium-review.googlesource.com/c/581796)
TurboAssembler changes that depend on the above
- [x] https://chromium-review.googlesource.com/c/563658/  - [port CL](https://chromium-review.googlesource.com/c/583584/)
- [x] https://chromium-review.googlesource.com/c/559674/  - [port CL]( https://chromium-review.googlesource.com/c/583584/)
- [x] https://chromium-review.googlesource.com/c/519267/

CLs to port after above are done:
- [x] https://chromium-review.googlesource.com/565721 - [port CL](https://chromium-review.googlesource.com/586641)
- [x] https://chromium-review.googlesource.com/570054 - [port CL](https://chromium-review.googlesource.com/586675)
- [x] https://chromium-review.googlesource.com/569069 - [port CL](https://chromium-review.googlesource.com/c/587228/)
- [x] https://chromium-review.googlesource.com/570023 - [port CL](https://chromium-review.googlesource.com/c/587228/)
- [x] https://chromium-review.googlesource.com/570485 - [port CL](https://chromium-review.googlesource.com/587610)
- [x] https://chromium-review.googlesource.com/563215 - [port CL](https://chromium-review.googlesource.com/587610)
- [ ] https://chromium-review.googlesource.com/571011 (cleanup)
- [x] https://chromium-review.googlesource.com/574494 - [port CL](https://chromium-review.googlesource.com/587610)
- [x] https://chromium-review.googlesource.com/576087 - [port CL](https://chromium-review.googlesource.com/c/588471/)
- [x] https://chromium-review.googlesource.com/577531 (verify)
- [ ] https://chromium-review.googlesource.com/576181 (cleanup)
- [x] https://chromium-review.googlesource.com/575975 (verify)
- [ ] https://chromium-review.googlesource.com/578029 (verify)
- [ ] https://chromium-review.googlesource.com/571448 (verify, wasm)
- [x] https://chromium-review.googlesource.com/577890 - [port CL](https://chromium-review.googlesource.com/c/588468/)

**Comment by jbajwa** [comment]
another [CL](https://chromium-review.googlesource.com/548078) for Delay generation of code stubs. For now not using this optimization, [CL](https://chromium-review.googlesource.com/c/555330/).

**Comment by jbajwa** [comment]
One more [CL](https://chromium-review.googlesource.com/561015) that depends on this.
For now, not using the HeapNumber handle [CL](https://chromium-review.googlesource.com/562656).
